INSERT INTO ARTISTS(ARTIST_NAME, ARTIST_HIRAGANA_NAME, ARTIST_ART_URL) VALUES('乃木坂46','のぎざかふぉーてぃしっくす','https://nogizaka46.com');
INSERT INTO ARTISTS(ARTIST_NAME, ARTIST_HIRAGANA_NAME, ARTIST_ART_URL) VALUES('日向坂46','ひなたざかふぉーてぃしっくす','https://hinatazaka46.com');
INSERT INTO ARTISTS(ARTIST_NAME, ARTIST_HIRAGANA_NAME, ARTIST_ART_URL) VALUES('櫻坂46','さくらざかふぉーてぃしっくす','https://sakurazaka46.com');
INSERT INTO ARTISTS(ARTIST_NAME, ARTIST_HIRAGANA_NAME, ARTIST_ART_URL) VALUES('ももいろクローバーZ','ももいろくろーばーぜっと','https://www.momocho.net');
INSERT INTO ARTISTS(ARTIST_NAME, ARTIST_HIRAGANA_NAME, ARTIST_ART_URL) VALUES('CANDY TUNE','きゃんでぃーちゅーん','https://candytune.asobisystem.com/');

INSERT INTO MEMBERS(ARTIST_ID, MEMBER_NAME, MEMBER_HIRAGANA_NAME, MEMBER_BIRTHDAY) VALUES(1,'五百城茉央','いおきまお','2005-07-29');
INSERT INTO MEMBERS(ARTIST_ID, MEMBER_NAME, MEMBER_HIRAGANA_NAME, MEMBER_BIRTHDAY) VALUES(1,'賀喜遥香','かきはるか','2001-08-08');

INSERT INTO MEMBERS(ARTIST_ID, MEMBER_NAME, MEMBER_HIRAGANA_NAME, MEMBER_BIRTHDAY) VALUES(2,'松田好花','まつだこのか','1999-04-27');

INSERT INTO MEMBERS(ARTIST_ID, MEMBER_NAME, MEMBER_HIRAGANA_NAME, MEMBER_BIRTHDAY) VALUES(3,'山崎天','やまさきてん','2006-09-28');

INSERT INTO MEMBERS(ARTIST_ID, MEMBER_NAME, MEMBER_HIRAGANA_NAME, MEMBER_BIRTHDAY) VALUES(5,'村川緋杏','むらかわびびあん','1999-02-03');